### PR TITLE
Fix sandbox and bump LLVM

### PR DESCRIPTION
**Pull request by matthias-springer**

### CODE REVIEW

**Review by ftynse — APPROVED** [review]

**Review by chelini — COMMENTED** [review]
Can we merge this pls? Thanks a lot.

**Comment by nicolasvasilache** [comment]
I would like to hold a bit on this if possible until #375. Otherwise merges are going to be more painful than necessary.

**Comment by chelini** [comment]
> I would like to hold a bit on this if possible until #375. Otherwise merges are going to be more painful than necessary.

OK. Thanks.

**Comment by nicolasvasilache** [comment]
I need to rebase this, taking the lock if you don't mind.

**Comment by nicolasvasilache** [comment]
Ran a bit ahead and landed this as #378 after fixing a few extra merge-related things.

**Pull request closed without merging**
