### PR TITLE
Iterators: Implement lowering of iterator state type and ops.

### PR DESCRIPTION
**Pull request by ingomueller-net**
This PR depends on and therefore includes #605 and #606.

### CODE REVIEW

**Review by nicolasvasilache — COMMENTED** [review]
We need some ops parsing/printing test here.

**Review by nicolasvasilache — CHANGES_REQUESTED** [review]
Sorry spoke too soon, we need to ensure the roundtripping works properly and we need tests for that: `mlir-opt %s | mlir-opt`

**Review by nicolasvasilache — APPROVED** [review]

**Comment by ingomueller-net** [comment]
> We need some ops parsing/printing test here.

This is actually a comment for #606 and I have addressed it there.

**Comment by ingomueller-net** [comment]
> Sorry spoke too soon, we need to ensure the roundtripping works properly and we need tests for that: `mlir-opt %s | mlir-opt`

Dito: related to #606 and addressed there.

**Pull request merged**
