### PR TITLE
[LLVM] Update submodule to latest version from Feb. 15 (e769fb86).

### PR DESCRIPTION
**Pull request by ingomueller-net**
This PR depends on and, therefor, includes #793 (which removes the indexing dialect).

~~The PR is still missing changes to make the indexing dialect work with the upstream changes:~~

- [x] Make indexing dialect work. @makslevental Could you take a look?

### CODE REVIEW

**Comment by makslevental** [comment]
I moved `_get_int_int_array_attr` to `_ods_common` recently and that's what broken here. I'll commit ontop and fix in a bit.

**Comment by ingomueller-net** [comment]
Ah, good to know! I saw that it was removed from its old place; I hadn't seen its new place.

But there's more: the transition from Attributes to Properties requires the rewriting of some things and I didn't manage to do it for the canonicalization pattern of `ARangeOp`.

Thanks a lot!

**Review by jpienaar — APPROVED** [review]
I'm generally pro dropping these, always there in revision history if we need to revive it.

**Comment by makslevental** [comment]
> I'm generally pro dropping these, always there in revision history if we need to revive it.

Repeating offline comment here: feel free to drop `indexing` (or whatever portions I'm codeowner of) entirely - I doubt I'll have time/bandwidth to come back to it (at least here, in this form). I'd commit on top here but this is a PR from a fork...

**Comment by ingomueller-net** [comment]
OK, I rebased this on #793, which removes the indexing dialect. I kept a branch [here](https://github.com/iree-org/iree-llvm-sandbox/tree/wip-bump-llvm-indexing) with my WIP effort of updating it to the current version of LLVM in case someone ever wants to pick it up again.

**Pull request merged**
